### ISSUE TITLE
Configuration issue: Mosquitto with Lighttpd Websocket

### ISSUE THREAD

**Issue by priyankaTel** [iosphere/mosquitto#1]
Hello,
@ralight,

I am verifying lighttpd + mod_websocket with mosquitto broker.
Reference - http://oriolrius.cat/blog/tag/websockets/

I am facing continuous disconnection ( Socket error on client <client-id>, disconnecting. ). Logs from MQTT(mosquito) broker are provided below.

Message Published at local time:: 2016:05:20:02:04:20
1463709860: New client connected from 169.254.80.8 as web_32 (c1, k60).
1463709860: Sending CONNACK to web_32 (0, 0)
1463709860: Received UNSUBSCRIBE from web_32
1463709860: Socket error on client web_32, disconnecting.
1463709862: New connection from 169.254.80.8 on port 1883.
1463709862: Socket error on client <unknown>, disconnecting.
1463709862: New connection from 169.254.80.8 on port 1883.

Any help is appreciated

**Comment by ralight** [comment]
I've not had anything to do with lighttpd for a long time now, I'd suggest trying the built in websockets support instead.

**Comment by weitzj** [comment]
Closing this issue. The Main repo is now at https://github.com/eclipse/mosquitto 
You should fill an issue there
