### ISSUE TITLE
Setting configuration for Mosquitto?

### ISSUE THREAD

**Issue by nilavkhatiwada** [iosphere/mosquitto#3]
[#include <cstdio>
#include <cstring>
#include <iostream>

#include "myMosq.h"
#include <mosquittopp.h>
#include "Configuration.h"
#include "Databases.h"

using namespace std;

Configuration configuration;

myMosq::myMosq(const char * _id,const char * _topic, const char * _host, int _port) : mosquittopp(_id)
 {
 mosqpp::lib_init();        // Mandatory initialization for mosquitto library
 this->keepalive = 60;    // Basic configuration setup for myMosq class
 this->id = _id;
 this->port = _port;
 this->host = _host;
 this->topic = _topic;
 connect_async(host,     // non blocking connection to broker request
 port,
 keepalive);
 loop_start();            // Start thread managing connection / publish / subscribe
 };

myMosq::~myMosq() {
 loop_stop();            // Kill the thread
 mosqpp::lib_cleanup();    // Mosquitto library cleanup
 }

bool myMosq::receive_message()
 {
	int set = subscribe(NULL, configuration.subscriptionTopic.c_str(),2);
	return set;
 }

bool myMosq::send_message(string responseMessage) {
	int ret = publish(NULL,configuration.producerTopic.c_str(),strlen(responseMessage.c_str()),responseMessage.c_str(),1,false);
	return (ret = MOSQ_ERR_SUCCESS);
}

void myMosq::on_disconnect(int rc) {
 std::cout << ">> myMosq - disconnection(" << rc << ")" << std::endl;
 }

void myMosq::on_connect(int rc)
 {
 if ( rc == 0 ) {
 std::cout << ">> myMosq - connected with server" << std::endl;
 } else {
 std::cout << ">> myMosq - Impossible to connect with server(" << rc << ")" << std::endl;
 }
 }

void myMosq::on_message(const struct mosquitto_message *message) {

	char * pchar = (char*)(message->payload);
	string str(pchar);
	writeToDatabase(str);
}

void myMosq::on_subscribe(int mid, int qos_count, const int *granted_qos)
{
	std::cout << ">> subscription succeeded (" << mid << ") " << std::endl;
}

void myMosq::on_publish(int mid) {
	std::cout << ">> myMosq - Message (" << mid << ") succeed to be published " << std::endl;
}

void myMosq::writeToDatabase(string query) {

	Databases* database = new Databases(configuration.db,
			configuration.dbPort, configuration.username, configuration.password,
			configuration.schema);
	database->writeDatabase(query);

	if(database->responseMessage == "") {
		database->responseMessage = "SUCCESS";
	}

	this->send_message(database->responseMessage);
}

void myMosq::on_unsubscribe(int mid) {
	cout<<"unscubscribed";
};](url)

This is the code for my mosquitto program. Now I could not figure out how could i set the configuration attributes like persistence, persistence_location or autosave.interval

**Comment by weitzj** [comment]
@nilavkhatiwada The Main repo is now at https://github.com/eclipse/mosquitto 
You should fill an issue there.
