### ISSUE TITLE
how can i use tls method?

### ISSUE THREAD

**Issue by kerwin24** [iosphere/mosquitto#5]
Hi,I want to ask how can i use tls method?
I used it without tls . It's success.
now i want to use tls in QT with mosquittopp.h . 
This is my code
   ui->lineIP->setText(QString("0.0.0.0"));
    ui->linePort->setText(QString("8883"));
    QByteArray host = ui->lineIP->text().toLocal8Bit();
    QByteArray id = ui->lineID->text().toLocal8Bit();
    QByteArray pwd = ui->lineEdit->text().toLocal8Bit();
    QByteArray pws = ui->lineEdit_2->text().toLocal8Bit();
    port = ui->linePort->text().toInt();
    if (!port)
    {
        ui->linePort->clear();
        return ;
    }
    ui->connect->setDisabled(true);
    mosq = new qtmosq(id, false);
    mosq->tls_opts_set(1,"tlsv1",NULL);
    mosq->tls_set("/etc/mosquitto/ca_certificate/ca.crt",NULL,"/etc/mosquitto/certs/raspberrypi.crt","/etc/mosquitto/certs/raspberrypi.key",NULL);
    mosq->username_pw_set(pwd.data(),pws.data());
    mosq->connect_async(host.data(), port);
    mosq->loop_start();
    connect (mosq, SIGNAL(connectEnable()), this, SLOT(connectEnabled()));
    connect (mosq, SIGNAL(subscribed()), this ,SLOT(subscribed()));
    connect (mosq, SIGNAL(connected()), this, SLOT(connected()));
    connect (mosq, SIGNAL(messageSent(bool)), this, SLOT(setMessageStatus(bool)));
    connect (mosq, SIGNAL(messageReceived(QString)), this, SLOT(showMessage(QString)));
Is there anything I made wrong?I need your recommendations to solve this issue.Thank you

**Comment by felixLam** [comment]
This is a mirror/fork of the original repository, we cannot provide support. Sorry
